version: '3.3'

variables:
  DOCKER_USERNAME: bburich
  TAG: latest

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - ../.env
    restart: always
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      interval: 5s

  backend:
    image: ${DOCKER_USERNAME}/foodgram_backend:${TAG}
    volumes:
      - static_backend:/app/static_backend/
      - media_value:/app/media/
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    image: ${DOCKER_USERNAME}/foodgram_frontend:${TAG}
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    env_file:
      - ../.env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_backend:/var/html/static_backend/
      - media_value:/var/html/media/
    depends_on:
      - frontend
    restart: always

volumes:
  static_backend:
  media_value: