# Generated by Django 2.2.28 on 2022-09-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220925_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name_plural': 'Recipe Ingredients'},
        ),
    ]
