# Generated by Django 2.2.28 on 2022-09-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220823_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
