# Generated by Django 2.2.28 on 2022-09-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220901_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingridient',
            new_name='ingridients',
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
