# Generated by Django 2.2.28 on 2022-09-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20220912_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(upload_to='recipes/images/'),
        ),
    ]
