# Generated by Django 2.2.28 on 2022-09-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220925_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
    ]
